[module]
  [module.hugoVersion]
    extended = true
    min = "0.87.0"
    max = "0.120.4"

baseURL = "/"
languageCode = "de"
 [author]
   name = "Tim Birnkraut"
   image = "img/profilepic.jpeg"
   headline = "Hi, my name is Tim"
